// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwi9qORb03GEf6Dz1pCWzY_OGX-e0Ht3g',
    appId: '1:868259078848:web:82df148ca5a0a99eb44325',
    messagingSenderId: '868259078848',
    projectId: 'video-player-f24db',
    authDomain: 'video-player-f24db.firebaseapp.com',
    storageBucket: 'video-player-f24db.appspot.com',
    measurementId: 'G-YGB48D5TVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EvJU9ovG3s_RG4EVk4FySI1agp3m3nA',
    appId: '1:868259078848:android:7f5164e583b11db4b44325',
    messagingSenderId: '868259078848',
    projectId: 'video-player-f24db',
    storageBucket: 'video-player-f24db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPapcHsNWzCgAuDIxjZQECrmqUPEr_ZY',
    appId: '1:868259078848:ios:0d068565e5fc7838b44325',
    messagingSenderId: '868259078848',
    projectId: 'video-player-f24db',
    storageBucket: 'video-player-f24db.appspot.com',
    iosBundleId: 'com.example.lilacTask2',
  );
}
